# Generated by Django 5.0.2 on 2024-04-17 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativas', models.DecimalField(decimal_places=1, max_digits=1)),
                ('vidas', models.DecimalField(decimal_places=1, default=6, max_digits=1)),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
