# Generated by Django 5.0.2 on 2024-04-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_usuario_vidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pontuacao',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tentativas',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
