# Generated by Django 5.0.2 on 2024-04-17 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_usuario_pontuacao_alter_usuario_tentativas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField()),
                ('palavra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.palavra')),
            ],
        ),
    ]
